### ISSUE TITLE
ReLERNN_TRAIN step has a problem: ValueError: The filepath provided must end in `.keras` (Keras model format)

### ISSUE THREAD

**Issue by jiangzy26** [kr-colab/ReLERNN#49]
Hi, I got an Error when I ran the TRAIN step, could you share your help? Thank you very much, here is my code:

/data2/software-use/ReLERNN/ReLERNN/ReLERNN_SIMULATE -v species.vcf \
-d myfile \
--demographicHistory species_plot.csv \
-u 3.3e-9 \
-l 1 \
-t 40 \
-s 123 \
-g genome.length.bed \
--unphased

/data2/software-use/ReLERNN/ReLERNN/ReLERNN_TRAIN -d myfile -t 20 -s 123
The output is :
 Total params: 76,002,769 (289.93 MB)
 Trainable params: 76,002,769 (289.93 MB)
 Non-trainable params: 0 (0.00 B)
Traceback (most recent call last):
  File "/data2/software-use/ReLERNN/ReLERNN/ReLERNN_TRAIN", line 130, in <module>
    main()
  File "/data2/software-use/ReLERNN/ReLERNN/ReLERNN_TRAIN", line 109, in main
    runModels(ModelFuncPointer=GRU_TUNED84,
  File "/data2/software-use/anaconda3/envs/ReLERNN_python/lib/python3.10/site-packages/ReLERNN/helpers.py", line 353, in runModels
    ModelCheckpoint(
  File "/data2/software-use/anaconda3/envs/ReLERNN_python/lib/python3.10/site-packages/keras/src/callbacks/model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=myfile/networks/weights.h5

**Comment by ThomasBrazier** [comment]
Hi,

I got the same error. Could you please share the solution ?

Best, 

Thomas

**Comment by wbooker** [comment]
Hey Thomas,

I had the same error, which seemed to be caused due to recent versions of keras requiring the .keras file. installing a previous version e.g pip install keras==2.15.0 got everything working

**Comment by ThomasBrazier** [comment]
Hi,
Thank you for the solution.
Best,
Thomas
