### ISSUE TITLE
The filepath provided must end in `.keras` (Keras model format)

### ISSUE THREAD

**Issue by Ste40** [kr-colab/ReLERNN#53]
Hello, 
I'm trying to test ReLERNN installation running the example_pipeline.sh and I'm having the following error during training step: 

Traceback (most recent call last):
  File "/home/quaranta/anaconda3/bin/ReLERNN_TRAIN", line 130, in <module>
    main()
  File "/home/quaranta/anaconda3/bin/ReLERNN_TRAIN", line 109, in main
    runModels(ModelFuncPointer=GRU_TUNED84,
  File "/home/quaranta/anaconda3/lib/python3.10/site-packages/ReLERNN/helpers.py", line 353, in runModels
    ModelCheckpoint(
  File "/home/quaranta/anaconda3/lib/python3.10/site-packages/keras/src/callbacks/model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=./example_output/networks/weights.h5

How can i solve? Thanks

**Comment by andrewkern** [comment]
this is likely an issue with your tensorflow version. are you using 2.16? try downgrading to tensorflow 2.15

**Comment by Ste40** [comment]
It worked! Thanks
